=== Hyperparticle/lct-master/charles-university/2017-npfl092/hw05/person.dtd
<!ELEMENT person (company,hobbies,home)>
<!ATTLIST person firstname CDATA #REQUIRED lastname CDATA #REQUIRED>

<!ELEMENT company (name,city)>
<!ATTLIST company id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT city (#PCDATA)>

<!ELEMENT hobbies (hobby*)>
<!ELEMENT hobby (#PCDATA)>
<!ATTLIST hobby rating CDATA #REQUIRED>

<!ELEMENT home (address,city)>
<!ELEMENT address (#PCDATA)>

=== Hyperparticle/lct-master/charles-university/2017-npfl092/hw05/person.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE person SYSTEM "person.dtd">
<person firstname="John" lastname="Smith">
  <company id="abc">
    <name>Funny Business</name>
    <city>Timbuktu</city>
  </company>
  <hobbies>
    <hobby rating="8">woodworking</hobby>
    <hobby rating="8">camping</hobby>
  </hobbies>
  <home>
    <address>123 fake st.</address>
    <city>Timbuktu</city>
  </home>
</person>
